# Admin
BTN_NEW_GROUP = "📁 Yangi guruh yaratish"
BTN_YEAR_GROUPS = "🗂 Yil bo'yicha guruhlar"
BTN_ADD_STUDENT = "➕ O'quvchi qo'shish (Bitta)"
BTN_EXCEL_UPLOAD = "📥 O'quvchilarni Exceldan yuklash"
BTN_STUDENT_LIST = "📋 O'quvchilar ro'yxati"
BTN_DEBT = "💸 Qarz yozish"
BTN_MONTHLY = "🔄 Oylik hisob-kitob"
BTN_TEST_UPLOAD = "📊 Test yuklash"
BTN_PUBLIC_UPLOAD = "📢 Ommaviy fayl/e'lon yuklash"
BTN_PUBLIC_TEST = "🧾 Ommaviy test natijasi"
BTN_DEBTORS_EXCEL = "📑 Qarzdorlar (Excel)"
BTN_ATTENDANCE = "🗓 Davomat"
BTN_IDS_EXCEL = "🆔 O'quvchi va Guruh ID lari (Excel)"
BTN_PAYMENT_CARDS = "💳 To'lov kartalari"

# User
BTN_CHECK_BALANCE = "📉 Oylik to'lov va Qarzni tekshirish"
BTN_PAY = "💳 To'lov qilish"
BTN_RATING = "🏆 O'quvchi reytingi"
BTN_HISTORY = "📅 Barcha testlar tarixi"
BTN_FILES = "📂 Yuklangan fayllar"
BTN_TEST_ARCHIVE = "📊 Test natijalari"
BTN_CONTACT_ADMIN = "✉️ Admin bilan bog'lanish"
